name: Build ZMK firmware

on:
  workflow_call:
    inputs:
      west_yml_path:
        type: string
        required: false
        default: "config/west.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - name: Checkout Dockerfile
        uses: actions/checkout@v4
      - name: Copy Files
        run: cp -r ./ /workspace/zmk-config
      - name: Test
        run: |
          pwd
          ls -al $(find . -type f)
          ls -al $(find /workspace/zmk-config -type f)
          ls -al /
          ls -al /workspace

