name: Publish Builder Image

on:
  workflow_call:
    inputs:
      west_yml_path:
        type: string
        required: false
        default: "config/west.yml"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    
    steps:
      - name: Chcekout West Config
        uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ inputs.west_yml_path }}
      # - name: Rename West Config
      #   run: |
      #     mkdir -p config
      #     mv "${{ inputs.west_yml_path }}" config/west.yml
      - name: Downcase repository name
        run: |
          echo "IMAGE_NAME=${{ github.repository }}" | tr '[:upper:]' '[:lower:]' >> $GITHUB_ENV
      - name: Test
        run: |
          echo ghcr.io/${{ env.image_name }}:${{ github.ref_name }}
          ls -l $(find . -type f)
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.image_name }}:${{ github.ref_name }}
